### PR TITLE
fix: allow fractional gas prices

### PR DESCRIPTION
**Pull request by ejfitzgerald**
## Overview

Allow the users to be able to specify float values as gas prices. This is helpful in networks other than `fetchhub` where integer gas prices would cause very high fee values.

### CODE REVIEW

**Review by solarw — APPROVED** [review]
lgtm

**Review by 5A11 — APPROVED** [review]
lgtm

**Comment by 5A11** [comment]
@ejfitzgerald any reason you have this as draft? Otherwise it is ready to merge.

**Comment by kapong** [comment]
hi, I'm from #291. I think you should use `math.ceil()` instead of  `int()` to cast to integer because it will be flooring gas value and have risk to fail request.

for me, I'm use [this method](https://stackoverflow.com/a/17511341) instead of import math and use `math.ceil`

**Comment by ejfitzgerald** [comment]
Hey @kapong - I have updated to `math.ceil` as you say I think that is a nice catch. I went with `math.ceil` in the end (as opposed to your method) because I think it clearer to read - but your method is cool 😁 

@5A11 happy for you to land this change provided you are happy with it

**Pull request merged**
