### PR TITLE
mdformat support added

### PR DESCRIPTION
**Pull request by solarw**
according to https://github.com/fetchai/cosmpy/pull/250

### CODE REVIEW

**Comment by solarw** [comment]
md files are not formatted!

**Comment by VijaySharma815** [comment]
mdformat repot the issue:
```
Error: File
"/cosmpy/docs/api/aerial/tx_helpers.md" is not formatted.
```


markdown lint report issue:
```
docs/api/aerial/client/__init__.md:162 MD024/no-duplicate-heading/no-duplicate-header Multiple headings with the same content [Context: "#### gas`_`strategy"]

```

**Comment by VijaySharma815** [comment]
@5A11 @solarw , 

`md-format` is doing a high level of formatting so we can use it.

**Comment by VijaySharma815** [comment]
@solarw , I raised the PR on top of your branch:
https://github.com/fetchai/cosmpy/pull/280

I have done all the required changes. whenever you get chance please have a look. 

cc: @5A11

**Comment by 5A11** [comment]
See https://github.com/fetchai/cosmpy/pull/280#issuecomment-1248318427

**Pull request closed without merging**
