### PR TITLE
Fix: codefactor.io issues

### PR DESCRIPTION
**Pull request by VijaySharma815**
Issue: https://github.com/fetchai/cosmpy/issues/245

Code factor: https://www.codefactor.io/ 

- [X] Fixed Docker Issues 
- [X] Fixed YAML issues 

For python issues: 
- Most of the issues raised for protos modules, which are around 3000-4000, for now, we are ignoring the proto module for any styling. 
- Some of the issues have already been addressed in my Open PR so once the following PR is merged I will check it again:
    - Add missing docstring: https://github.com/fetchai/cosmpy/pull/265
    - Re-enable pylint: https://github.com/fetchai/cosmpy/pull/251

### CODE REVIEW

**Review by solarw — APPROVED** [review]
LGTM

**Comment by VijaySharma815** [comment]
@solarw as per the codefactor.io:

```subprocess call with shell=True identified, security issue. ```

```
Found in [install_packages.py:38-39]
    text = subprocess.check_output(
        f"poetry export --with {groups}", shell=True, text=True
```

When I did the shell=False I am getting an error on my local:
```
FileNotFoundError: [Errno 2] No such file or directory: 'poetry export --with dev,docs,test
```

**Comment by VijaySharma815** [comment]
@5A11 apart for the above comment,

I have addressed all the issues from codefactor.io (except `protos` related issues)

**Comment by solarw** [comment]
> @solarw as per the codefactor.io:
> 
> `subprocess call with shell=True identified, security issue. `
> 
> ```
> Found in [install_packages.py:38-39]
>     text = subprocess.check_output(
>         f"poetry export --with {groups}", shell=True, text=True
> ```
> 
> When I did the shell=False I am getting an error on my local:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'poetry export --with dev,docs,test
> ```

`shell=True` is required. it's an utility script assuming not going to be used directly by developer/user
if possible - need to add an exclusion for this

**Review by solarw — APPROVED** [review]
LGTM

**Review by 5A11 — APPROVED** [review]

**Pull request merged**
