### PR TITLE
Trying to fix weird github actions error with protobuf version

### PR DESCRIPTION
**Pull request by MissingNO57**

### CODE REVIEW

**Comment by ejfitzgerald** [comment]
@5A11 - I had to make a similar change on my local change. Think that we should try and land this ASAP

**Comment by 5A11** [comment]
@MissingNO57 Is that the latest version that does not have the problem?

**Comment by daeMOn63** [comment]
Mostly to help finding this later - got the tests failing as well with an error similar to:
```
E   TypeError: Descriptors cannot not be created directly.
E   If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
E   If you cannot immediately regenerate your protos, some other possible workarounds are:
E    1. Downgrade the protobuf package to 3.20.x or lower.
E    2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
E   
E   More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

Installing the suggested version from this PR does fix it. Had to also change it from the  requirements.txt and requirements-dev.txt files to make the github actions happy.

**Comment by 5A11** [comment]
This is now fixed in #66

**Pull request closed without merging**
