### PR TITLE
gov module queries support

### PR DESCRIPTION
**Pull request by solarw**
gov module queries support

### CODE REVIEW

**Review by MissingNO57 — APPROVED** [review]
LGTM

**Review by 5A11 — COMMENTED** [review]
Could you add `:param` and `:return: as well (similar to bank). 
Also enable this docstring format in CI checks.

**Comment by solarw** [comment]
> Could you add `:param` and `:return: as well (similar to bank). Also enable this docstring format in CI checks.

done

**Review by 5A11 — APPROVED** [review]
lgtm

**Pull request merged**
